name: vibehear
description: "An accessibility companion that translates speech and trigger words into distinct vibrations."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.5.3
  vibration:
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.1
  google_fonts: ^8.0.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^21.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
  - lib/images/
  - lib/images/whatsapp.png
  - assets/porcupine_models/


